### PR TITLE
Use Coveralls for code coverage

### PR DESCRIPTION
**Pull request by rmccue**
Don't merge this one yet, just testing on this branch.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
These messages will get annoying. Can we pipe to Slack instead?

**Comment by rmccue** [comment]
Will switch to Slack. Do we want to leave the build status one as well?

**Comment by danielbachhuber** [comment]
> Do we want to leave the build status one as well?

Sorry, not sure I follow?

**Comment by rmccue** [comment]
screenshot 2015-05-10 23 02 35

Right now, it's just set to report here (should do it straight after Travis is done, so shouldn't block). We can set a minimum threshold (e.g. fail if it drops below x%), or a relative minimum threshold (e.g. fail if it drops by x%), but dunno whether we want that.

**Comment by danielbachhuber** [comment]
> Right now, it's just set to report here (should do it straight after Travis is done, so shouldn't block).

Oh, nifty. Works for me.

**Comment by rmccue** [comment]
Comments off. Still on me to sort out getting Slack hooked up with someone with Slack admin.

**Comment by rachelbaker** [comment]
@rmccue Sounds like we aren't connecting this to Slack, okay to merge?

**Comment by rmccue** [comment]
Forgot to merge this after talking with Sam, let's hit it.

**Pull request merged**
