### PR TITLE
Force `GET /wp/v2/media` to be limited to 'status' => [ inherit, private, trash ]

### LINKED ISSUE #1986: Abstract Attachment-specific conditionals to Attachments controller
There are a few instances of Attachment-specific conditionals in the Posts controller that would be better off in the Attachments controller:
- [ ] https://github.com/WP-API/WP-API/blob/a93ea66d361ae24882cd002b0fa0ff1503726522/lib/endpoints/class-wp-rest-posts-controller.php#L537-L539
- [ ] https://github.com/WP-API/WP-API/blob/a93ea66d361ae24882cd002b0fa0ff1503726522/lib/endpoints/class-wp-rest-posts-controller.php#L962-L972
- [ ] https://github.com/WP-API/WP-API/blob/a93ea66d361ae24882cd002b0fa0ff1503726522/lib/endpoints/class-wp-rest-posts-controller.php#L1615
- [ ] https://github.com/WP-API/WP-API/blob/a93ea66d361ae24882cd002b0fa0ff1503726522/lib/endpoints/class-wp-rest-posts-controller.php#L1636

### PR DESCRIPTION
**Pull request by danielbachhuber**
Attachments can only ever have the `inherit`, `private`, and `trash` statuses.

Fixes #1986

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by rmccue** [comment]
> Attachments can only ever have the inherit status.

Is this necessarily true? Can plugins create attachments with a different status, or is it forced to `inherit` in WP?

**Comment by danielbachhuber** [comment]
> Is this necessarily true? Can plugins create attachments with a different status, or is it forced to inherit in WP?

Oh, huh. `wp_insert_post()` has:

```
if ( 'attachment' === $post_type && ! in_array( $post_status, array( 'inherit', 'private', 'trash' ) ) ) {
    $post_status = 'inherit';
}
```

**Comment by danielbachhuber** [comment]
I'll update it to make sure we accommodate each of the statuses, and there's corresponding tests.

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
Build fails because `unregister_post_type()` isn't yet available in the nightly.

**Pull request merged**
