### PR TITLE
Use discrete `title` for categories and tags

### PR DESCRIPTION
**Pull request by danielbachhuber**
They're separate schemas, so they should be named differently

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by rachelbaker** [comment]
@danielbachhuber Unit tests for `register_rest_field` with the Terms controller would be :100:

**Comment by danielbachhuber** [comment]
> Unit tests for register_rest_field with the Terms controller would be

Good call. Updating.

**Comment by danielbachhuber** [comment]
@WP-API/amigos updated with `test_get_additional_field_registration`

**Pull request merged**
