### PR TITLE
Change users schema order to be order of importance instead of alpha

### PR DESCRIPTION
**Pull request by rachelbaker**

### CODE REVIEW

**Comment by rachelbaker** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
> order of importance 

How did you determine this?

**Comment by rmccue** [comment]
:+1:

@danielbachhuber At a guess, just a design decision.

**Comment by rachelbaker** [comment]
@danielbachhuber how did you determine the order of the other endpoint schemas?

I moved `id` to the top and then tried to order the other properties by making educated guesses on likely use.

I can see there are some things I missed here:
 * `url` should probably move up
 * `capabilities` and `extra_capabilities` should be under `role` and `roles`

I will refresh this PR when I can.

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

I moved `url` to under `email`, where it appears in the User Profile in the dashboard. I already see `capabilities` and `extra_capabilities` to be under `role` and `roles`.

**Pull request merged**
