### PR TITLE
Throw error if request uses unavailable `edit` context

### LINKED ISSUE #861: Passing context=edit to a user when unauthorized does not give an error
We should always be explicit if you try and access data without permission. Introduced in #838.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #861

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@rmccue How do you feel about this forced downgrade logic? https://github.com/WP-API/WP-API/pull/838/files#diff-6a242a8d43b6c0aa73da8f01c1324859R63

I think this is another instance of #702 — there's a loose coupling between contexts and capabilities right now that's causing regular problems.

**Comment by rmccue** [comment]
> How do you feel about this forced downgrade logic?

I'd *much* rather return an error; that's the main point of contexts in the first place. As I said on #702:

> Additionally, right now setting `context` either succeeds (returns all data for that context) or fails (returns no data/an error), which is kind of nice in that you immediately know if you can't access the data.

**Comment by rmccue** [comment]
With this pull request: this doesn't handle `/comments` as well, correct?

**Comment by danielbachhuber** [comment]
Correct, it doesn't. I don't think the solution is to fix all of these context-related issues in a one-off manner. If we want contexts to have a strong correlation to capability checks, we need a better abstraction

**Comment by danielbachhuber** [comment]
Continuing in #1033

**Pull request closed without merging**
