### PR TITLE
Check if post status is public in check_read_permission()

### PR DESCRIPTION
**Pull request by vlood**
Before this change all posts with custom post statuses were left behind.

### CODE REVIEW

**Comment by rachelbaker** [comment]
@vlood Good catch.  Thank you for the patch.  This PR needs two things to be merged:

1. Spacing adjustments to match the WordPress Coding Standards: https://make.wordpress.org/core/handbook/coding-standards/php/#space-usage

2. Unit tests to confirm that custom post statuses set to public are allowed.  

Can you update your PR?

**Comment by vlood** [comment]
Yep, will do this :)

**Comment by rmccue** [comment]
@vlood Any updates here? :)

**Comment by vlood** [comment]
Yeah, I've written some tests, but have no PHPUnit setup on my environment and just had my laptop destroyed, so I got other issues to face. I can update the pull request with the tests (and the spacing convention applied), if this is okay with you?

**Comment by rmccue** [comment]
Ouch, sucks to hear that!

Any updates you have are fine (even if non-functional); we can fix up any other issues on our end.

**Comment by vlood** [comment]
Okay, this should be it - c5f618a comes with the tests and stuff :)

**Comment by vlood** [comment]
The PR is refreshed after the last changes in the file structure that made it's previous commits impossible for automatic merge. Let me know if you need anything else in order to have this one accepted.

**Comment by danielbachhuber** [comment]
Closing in favor of #1765

**Pull request closed without merging**
