### PR TITLE
Fix error on Post Update of featured_image (WP-API/WP-API#444)

### PR DESCRIPTION
**Pull request by rhurling**

### CODE REVIEW

**Comment by rhurling** [comment]
there was already a pull request #727 , but for the develop branch.
this pull request is against the one-dot-one branch so that the version can be bumped and pushed to w.org

**Comment by rmccue** [comment]
Thanks for the patch! This needs to wrap `$thumbnail` in `json_ensure_response`, as well as checking for an error before using it (`is_wp_error( $thumbnail )`)

**Comment by rhurling** [comment]
Now that 1.2 is released, could someone move this Pull Request to the 1.2.1 Milestone?
Or should I create a new one (against the master branch)?

**Comment by danielbachhuber** [comment]
This is already fixed on master https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-media.php#L436

**Pull request closed without merging**
