### PR TITLE
Add `template` parameter to Page response

### LINKED ISSUE #748: Missing `template` attribute for Pages
Any post type that is hierarchical and supports `page-attributes` should include a `template` attribute, in addition to `menu_order`.

Related #718, #605

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #748

Related #718, #605

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Still need to do updating

**Comment by danielbachhuber** [comment]
Hm, some bug :(

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by rachelbaker** [comment]
Merged #909

**Pull request merged**
