### PR TITLE
Add WordPress Dependency

### PR DESCRIPTION
**Pull request by joehoyle**

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks for the PR! With the REST API, we follow the [WordPress coding standards](https://make.wordpress.org/core/handbook/coding-standards/php/); can you please update the code here to match those?

**Comment by pento** [comment]
I have concerns about the performance of the code in this PR. I think it needs to be significantly refactored before it can be considered for merge.

**Comment by samwilson** [comment]
1,613 files? Is this all of Wordpress or something?

Wouldn't it be better to add it as a Composer dependency?

**Comment by aaronjorbin** [comment]
Do you think it might make more sense to include Drupal instead?  Have all the options been explored?

**Comment by samwilson** [comment]
Hm yes, I see what you mean @aaronjorbin! Could all of MediaWiki please be included? It's not huge, and might, umm, help? :-P

**Comment by rmccue** [comment]
I'm locking this topic, there are too many Australians here.

**Comment by rmccue** [comment]
I apologise, must be something in the water here in NZ. Reopened.

**Comment by samwilson** [comment]
Ahg you're just rubbing it in that you've got nicer water than Perth! :-)

**Comment by pdewouters** [comment]
Isn't there already a PR to include the Internet? it would make this one redundant.

**Comment by kadamwhite** [comment]
Implementing a highly usable, back-compatible server-side application for WYSIAlmostWYG content management for content already addressable by API endpoints is deemed out of scope for this project.

**Pull request closed without merging**
