### PR TITLE
Return post data from post delete endpoint

### LINKED ISSUE #618: Delete requests shouldn't return response with message body
In the user's controller, we return this response when the delete request is successful:

```
return array( 'message' => __( 'Deleted user' ) );
```

As a matter of practice, I don't think we should *ever* return a "message" in a 2xx response. "Success" is implied by the response code, and it's inconsistent generally.

@WP-API/amigos opinions?

### PR DESCRIPTION
**Pull request by rmccue**
Fixes #618.

### CODE REVIEW

**Comment by rmccue** [comment]
This one's on me, sorry. Will fix up ASAP.

**Comment by rmccue** [comment]
(Also needs unification with #789)

**Comment by nacin** [comment]
What needs discussion here?

**Comment by danielbachhuber** [comment]
> What needs discussion here?

#789

**Comment by rachelbaker** [comment]
Punting to Beta 2.

**Comment by danielbachhuber** [comment]
Handling in #1224

**Pull request closed without merging**
