### PR TITLE
Add permission check for retrieving the /posts endpoint when context=…

### PR DESCRIPTION
**Pull request by danielpunkass**
…edit

By extension of the fact that getting any individual post yields a forbidden context error when the context=edit and the user is not authorized, the user should also not be permitted to list any post items when unauthorized.

### CODE REVIEW

**Comment by rachelbaker** [comment]
@danielpunkass Great catch that we were missing this permission check.  I don't know if `edit_posts` is the correct permission check here, though.  

@WP-API/amigos Any suggestions for the permission check we should be using here?  I was thinking something like `current_user_can( $this->post_type->cap->create_posts );`

**Comment by danielbachhuber** [comment]
> Any suggestions for the permission check we should be using here? I was thinking something like current_user_can( $this->post_type->cap->create_posts );

Why not `current_user_can( $this->post_type->cap->edit_posts );` ?

**Comment by rachelbaker** [comment]
> Why not current_user_can( $this->post_type->cap->edit_posts ); ?

WFM

**Comment by danielpunkass** [comment]
Ah, am I reading this correctly that it would tie the permissions to e.g. whether the user has the ability to edit pages, or a custom post_type? I guess $this->post_type is set as a consequence of the specific endpoint e.g. /posts -> "post", etc? Sounds good to me, I'll update the pull request later tonight probably.

**Comment by rachelbaker** [comment]
Merged #1412

**Pull request merged**
