### PR TITLE
Support for getting a post with a custom public status

### PR DESCRIPTION
**Pull request by danielbachhuber**
Previously #787

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
Hm. Scratch that. Need to figure out what's broken.

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by joehoyle** [comment]
:+1: looks good!

**Pull request merged**
