### PR TITLE
Expose basic author details when user has published posts

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #837

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
@rachelbaker any thoughts as to why the tests fail?

**Comment by rachelbaker** [comment]
@danielbachhuber I have an idea.  Looking into it now.

**Comment by rachelbaker** [comment]
Merged #838 :zap:

**Comment by danielbachhuber** [comment]
Did you merge locally? How did you merge and close this pull request?

**Comment by rachelbaker** [comment]
@danielbachhuber Sorry, I missed that important step.  Thanks for catching it.  :disappointed:

**Pull request merged**
