### PR TITLE
Adding Access-Control-Expose-Headers header to allow pagination through ...

### PR DESCRIPTION
**Pull request by shprink**
...CORS

https://github.com/WP-API/WP-API/issues/542

I have tested, it works great

### CODE REVIEW

**Comment by joehoyle** [comment]
@rmccue is probably the best one to provide feedback here

**Comment by shprink** [comment]
If you merge do not forget to backport to v2 :)

**Comment by joehoyle** [comment]
@shprink this is against the `develop` branch, which is v2

**Comment by shprink** [comment]
Did not know develop was v2 :) thanks @joehoyle

**Comment by joehoyle** [comment]
From Slack, it's thought if the spec just allows access to all headers, that would be sane, as we don't have anything we want to hide.

**Comment by rmccue** [comment]
Closing, as it's now essentially a duplicate of #1529

**Pull request closed without merging**
