### PR TITLE
For clarity, rename `date` and `date_gmt` as `published` and `published_gmt`

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #605

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos Would love opinions on this.

**Comment by rmccue** [comment]
I'd prefer to leave this as `date`. Although i don't feel strongly about this, I think we need good reasons to deviate from core's naming (conceptually).

As an example, the main reason we deviated from core's naming for the user fields is because things like `display_name` and `nicename` are *terrible* naming when you expose the data. Ditto `name` to `slug` for the most part. I'm not sure the same exists for `date` vs `published`, but like I said, I don't feel strongly as long as we justify it :)

**Comment by danielbachhuber** [comment]
@nacin @markjaquith Opinions?

**Comment by danielbachhuber** [comment]
Punt on this — I'm not tied to it.

**Pull request closed without merging**
