### PR TITLE
Allow Cross Domain Basic auth

### PR DESCRIPTION
**Pull request by shprink**
and add paginations to exposed headers list so it can be retrieved by clients.

Related to this old PR I made: https://github.com/WP-API/WP-API/pull/802

### CODE REVIEW

**Comment by itsananderson** [comment]
:+1: Without this, it's impossible to do cross-origin AJAX requests for authenticated resources.

One thing I'm curious about is, should we add these headers in https://github.com/WP-API/WP-API/blob/818eec1291d059406289eab6e9bc4888c4473f68/plugin.php#L597

That's where the other `Access-Control-` headers are. Alternatively, we could move those other headers into this function.

Also, making those headers filterable would be great for custom plugin developers, who might want to expose or accept additional headers. I have an example of what that might look like in my "wp-api-cors" plugin. https://github.com/itsananderson/wp-api-cors/blob/09d0e5e13343b492fb0ab060b59bde836505220d/wp-api-cors.php#L51

**Comment by scottopolis** [comment]
+1

**Comment by rachelbaker** [comment]
Related #833 and #144

**Comment by rmccue** [comment]
:+1: Thanks for this! The build failed because of #1518, so merging this despite that.

**Comment by rickharrison** [comment]
How do you customize the `Access-Control-Allow-Headers` header? I am trying to work with a wordpress API and no methods will go through because `Content-Type` is not allowed.

**Comment by kadamwhite** [comment]
@rickharrison that's a good question, moved to its own issue: #2844

**Pull request merged**
