### PR TITLE
Remove compatibility repo for WordPress 4.3

### LINKED ISSUE #1794: Remove `core` submodule
Once WordPress 4.4 is released, we don't need to submodule `core` any more as the infrastructure will be included in WordPress core.

In doing so, we'll want to make sure we bump the minimum supported version to WordPress 4.4.

### PR DESCRIPTION
**Pull request by danielbachhuber**
WordPress 4.4 is now the latest stable release

Fixes #1794

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by joehoyle** [comment]
Before merging I just wanted to make all the @WP-API/amigos are aligned on dropping 4.3 and hence the compat repo, I guess we'd delete the core repo too. Let's discuss in tomorrow's meeting.

**Comment by rmccue** [comment]
:+1:

**Comment by rachelbaker** [comment]
:+1: from me

**Pull request merged**
