### PR TITLE
Conditionally model the term response based on its schema

### PR DESCRIPTION
**Pull request by danielbachhuber**
Similarly, only permit editing fields present on the schema

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by joehoyle** [comment]
Do we have the same issue on the other objects?

**Comment by danielbachhuber** [comment]
Yes. I've just been running into the issue piecemeal, as I extend the controllers.

**Comment by danielbachhuber** [comment]
Related #2416

**Pull request merged**
