### PR TITLE
Hook docs: lib/endpoints/class-wp-rest-posts-controller.php

### PR DESCRIPTION
**Pull request by adamsilverstein**
* Add hood docs where missing
* some language cleanup for consistency

See https://github.com/WP-API/WP-API/issues/1549

### CODE REVIEW

**Comment by rachelbaker** [comment]
@adamsilverstein WPCS is flagging this PR for an extra line break.  Can you fix?

```
FILE: ...d/WP-API/WP-API/lib/endpoints/class-wp-rest-posts-controller.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1151 | ERROR | [x] Functions must not contain multiple empty lines
      |       |     in a row; found 2 empty lines
----------------------------------------------------------------------
```

**Comment by adamsilverstein** [comment]
Doh! Will fix :)

**Comment by adamsilverstein** [comment]
@rachelbaker Updated: removed whitespace, builds should pass now.

**Comment by rachelbaker** [comment]
Merged #1562.  Thank you (again) for your service @adamsilverstein!

**Pull request merged**
