### PR TITLE
Add Terms Controller Collection Args Details

### PR DESCRIPTION
**Pull request by rachelbaker**
* Add missing collection args details to the Terms Controller
     * fill-in details for the `per_page`, `page`, `hide_empty`, and `search` args that are already handled in the get_items method
     * add a `sanitize_callback` to the `order` arg
     * add a `sanitize_callback` and add missing valid values to the enum array for the `orderby` arg
 * Don't hardcode the `hide_empty` collection arg to being false in `get_items` method

### CODE REVIEW

**Comment by rachelbaker** [comment]
@WP-API/amigos #reviewmerge

**Comment by rachelbaker** [comment]
Related #1581

**Comment by danielbachhuber** [comment]
If we're exposing `hide_empty` as an argument now, can we add a test for it?

Also, I think I didn't expose it originally because I wanted to have a conversation about its naming. Should we rename it? Querying posts has `with_comments`, so it could become `with_posts`

**Comment by rachelbaker** [comment]
@danielbachhuber I added a test for `hide_empty`. I am just trying to fill out our collection args for the documentation, and don't feel strongly about renaming it.

**Comment by danielbachhuber** [comment]
> I added a test for hide_empty. I am just trying to fill out our collection args for the documentation

Thanks, makes sense.

> don't feel strongly about renaming it.

@rmccue @joehoyle opinions?

**Comment by rmccue** [comment]
Hmm, `hide_empty` is the more generic term there, so it'd make sense to make it consistent on that instead, but I'm wary of having to rename stuff particularly when it's in WP Query (which everyone knows).

Merging in the meantime, we can continue discussing the change though.

**Pull request merged**
