### PR TITLE
Use Compact links for embedded responses if they are available.

### PR DESCRIPTION
**Pull request by joehoyle**
This fixes curies compatibility with 4.5, and doesn't fatal under 4.4

### CODE REVIEW

**Comment by joehoyle** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
@joehoyle Why don't any of the tests need changing?

**Comment by joehoyle** [comment]
@danielbachhuber all the tests are set up to use the full-uris, not compact URIs, we have a helper `rest_extand_curies` function or something similar.

**Comment by danielbachhuber** [comment]
Ok.

**Pull request merged**
