### PR TITLE
Let featured images forever be known as featured media

### LINKED ISSUE #2033: Rename `featured_image` attribute to `featured_media`
Our `_link` is `https://api.w.org/featuredmedia` intentionally.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Why shouldn't you be able to feature other media too?

Fixes #2033

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by joehoyle** [comment]
My only concern here is that we are telling clients "this is a piece of media", so the client then needs to work out if it's some media it can display as an image. I know that's probably the case right now (technically) as I could have an audio object as the "feature image", but given it's stored in the db as Thumbnail ID, I don't know if there's a legitimate case for saying WordPress will support anything other than images in that (protected) meta key.

**Comment by danielbachhuber** [comment]
Should we change the `_link` to `featuredimage` then?

**Comment by danielbachhuber** [comment]
We're sticking with `featured_media`. Discussion in https://wordpress.slack.com/archives/core-restapi/p1453386374005100

**Pull request merged**
