### PR TITLE
#790 wp die handler

### LINKED ISSUE #790: Add special handling for wp_die
We need to add a `wp_die_handler` filter so we can return a response when WordPress evokes `wp_die`.

Reference link to how Jetpack handles this: https://github.com/Automattic/jetpack/blob/a8f890c21db29f0d4ec22734fbb19b74cfa45bb1/class.json-api.php#L554

### PR DESCRIPTION
**Pull request by BE-Webdesign**
Fixes #790, #1660, #1784.  Adds a wp_die() handler for the WP REST API.  Not sure if this is the best implementation.  Would love some feedback and will probably mull over it a bit before it is ready for merge.

### CODE REVIEW

**Comment by BE-Webdesign** [comment]
Need to check update handler for duplicate comments as well so a comment can't be edited to a duplicate.  Also there was a skipped test that I did not unskip.

**Comment by BE-Webdesign** [comment]
Just need an O.K. on the implementation.  Not sure if I am sold on it entirely myself though.

**Comment by danielbachhuber** [comment]
> Just need an O.K. on the implementation.

I think the prior consensus was that we needed to abstract away the use of `wp_die()` in core for the functions we care about. If you wanted to prepare patches for those instances, we might be able to get them in 4.6-early

**Comment by BE-Webdesign** [comment]
Okay, I can't do anything today but can probably whip something up tomorrow.  Is there already a trac ticket?

**Comment by danielbachhuber** [comment]
> Is there already a trac ticket?

I don't know, actually. Probably worth discussing at Monday's meeting.

**Comment by BE-Webdesign** [comment]
Closing out as this was decided to be handled in a core patch of comments.

**Pull request closed without merging**
