### PR TITLE
Filter available page templates instead of writing to fs

### LINKED ISSUE #956: Unit tests assume they can write to stylesheet directory

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #956

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #review

**Comment by BE-Webdesign** [comment]
Looks good to me, clean fix!

**Comment by danielbachhuber** [comment]
Codecov failure — ignoring.

**Comment by rmccue** [comment]
:raised_hands: Hopefully tests will no longer fail for me!

**Pull request merged**
