### PR TITLE
Add argument swapping and comments for multiple placeholders.

### PR DESCRIPTION
**Pull request by mayukojpn**
See also:

Argument swapping
http://php.net/manual/en/function.sprintf.php#example-5473

Descriptions
https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions

### CODE REVIEW

**Comment by mayukojpn** [comment]
@miya0001 Can you test this with https://github.com/mayukojpn/wp-api-i18n/tree/ja-fix-placeholder ?

**Comment by miya0001** [comment]
I'm sorry, I don't have any idea to test it.
But this PR looks fine. 😄

**Comment by miya0001** [comment]
Ah, I thought comments should be removed.

```
/* translators: 1: parameter, 2: minimum number */
```

**Comment by mayukojpn** [comment]
@miya0001 Thank you! I removed some comments.

**Review by rmccue — APPROVED** [review]

**Comment by rmccue** [comment]
Thanks! ✨

**Pull request merged**
