### PR TITLE
Pagination headers for comment collection queries

### LINKED ISSUE #1186: Paginate comment queries and limit by default
Same as #534 and #537

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #1186

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
Hm. I have no idea why this test is failing.

**Comment by joehoyle** [comment]
@danielbachhuber due to the larger amount of tests the "invalid" id's actually existed. I updated to a sufficiently high number to avoid this.

**Comment by danielbachhuber** [comment]
Classic. Thanks!

**Pull request merged**
