### PR TITLE
Fix path for tag and category `_link`; adds tests

### PR DESCRIPTION
**Pull request by danielbachhuber**
From #2104
Related #2109

### CODE REVIEW

**Comment by joehoyle** [comment]
@danielbachhuber I know you want to move ahead with getting things merged, but I think it's more important that we have peer code review on all pull-requests than making things move fast and bypassing the code review process, as a matter of precedent. At the least, we should discuss an exception to this, as right now I'm not sure why you have merged a few of your own PRs. Is this because they are seemed too minor to warrant code review?

**Comment by danielbachhuber** [comment]
> I know you want to move ahead with getting things merged, but I think it's more important that we have peer code review on all pull-requests than making things move fast and bypassing the code review process, as a matter of precedent.

I, too, typically prefer pre-merge code review in principle.

In practice, pre-merge peer code review has proven to hamper the forward progress of the project because there are often days where no one else on the team responds to pings, emails, etc. For our current situation, I think requiring pre-merge code review on all pull requests is a matter of principle getting in the way of pragmatism.

I _do_ think everyone on the team should be reading every pull request, regardless of whether it's pre- or post-merge, and leaving comments / opening issues / creating new pull requests if they find something they want to discuss. Issues and pull requests are cheap.

> At the least, we should discuss an exception to this, as right now I'm not sure why you have merged a few of your own PRs. Is this because they are seemed too minor to warrant code review?

Three reasons:
1. Aforementioned point about principle vs. pragmatism.
2. It's a docs fix or some other minor issue.
3. I am comfortable with the code, and feel reasonably confident in the tests I've written around solving the issue.

I've purposefully avoided working on more controversial issues, because I know I need feedback on those and the feedback cycle is so slow.

**Comment by kadamwhite** [comment]
> I am comfortable with the code, and feel reasonably confident in the tests I've written around solving the issue.

I'm uncomfortable with this sentiment because it's bitten me really hard on other projects, both in cases where I was the one committing and where it was a teammate. I trust @danielbachhuber's code, but I'm not qualified to review much of it—this is a team project, and I'd prefer it to have review and move slower than to rush forward without those safeguards. I don't think hurrying will gain us anything, and it has the capacity to hurt: I still think 1.0 was released a month early, in the rush to make a plugin proposal window, and I'd prefer to avoid seeing us repeat that.

That said, I'd prefer to hear from @joehoyle @rachelbaker @rmccue et al about when (or whether) you'd realistically be able to get more involved, because it's been a bit of a solo game on slack for @danielbachhuber lately and I know that's been frustrating.

Doc fixes total :+1: though, docs have enough entropy as it is :)

**Comment by danielbachhuber** [comment]
> > I am comfortable with the code, and feel reasonably confident in the tests I've written around solving the issue.
> 
> I'm uncomfortable with this sentiment because it's bitten me really hard on other projects, both in cases where I was the one committing and where it was a teammate.

Don't get me wrong — I've written buggy code in the past, and will continue to write buggy code in the future. We're also commenting on a PR I submitted to fix a bug I introduced.

But, importantly, pre-merge code review doesn't protect you from introducing bugs to the codebase either. In fact, I don't believe that pre-merge code review _necessarily_ ensures fewer bugs are introduced into the codebase. There's [some research supporting this](http://research.microsoft.com/apps/pubs/?id=242201). I do believe TDD and automated code analysis, on a whole, ensures fewer bugs are introduced to the codebase. I think code review is primarily value for discussion, and distributing knowledge of the codebase throughout a team of developers.

>  I don't think hurrying will gain us anything, and it has the capacity to hurt: I still think 1.0 was released a month early, in the rush to make a plugin proposal window, and I'd prefer to avoid seeing us repeat that.

Although I wasn't involved in the 1.0 release and am not aware of perceived flaws you're referring to, I don't intend to make any design or code compromises in order to meet an arbitrary deadline. I think 2.0 will be ready when [all issues in the 2.0 milestone](https://github.com/WP-API/WP-API/milestones/2.0) are addressed. If I think of _anything_ to consider for 2.0, I create an issue and file it against 2.0.

**Comment by kadamwhite** [comment]
I realize I conflated "we don't have sufficient code review" with "we are rushing to meet a deadline," which in retrospect I think was unfair to all involved. I appreciate and recognize the diligence you and the rest of the API team are displaying as we work towards 2.0.

> I think code review is primarily value for discussion, and distributing knowledge of the codebase throughout a team of developers.

To revise my original concerns, I do think that it's disappointing that the entire team hasn't had the availability to distribute the knowledge of some of these changes equally; inconsistent time allocation's a risk in any open-source project, large ones more than most. Much of my frustration is also that I personally don't have the time to understand the plugin's internals to a degree where I can be useful to this process.

For context on the 1.0 comments, it's been 2 years so I'd need to dig through the repo for specifics, but the perceived flaw was that notable PRs _e.g._ for handling taxonomy collections were still in-flight, then the 1.0 version increased the complexity of completing that work because it prohibited breaking changes. It wasn't that any feature was misbehaving; didn't mean to give that impression.

**Comment by joehoyle** [comment]
Whatever the outcome, I strongly believe this should have been discussed before decided to merge our own PRs, that was my main point. There may be merit to the above arguments, but those should be decided with the buy in the from the rest of the team.

**Pull request merged**
