### PR TITLE
Add filter to taxonomy output in post object.

### PR DESCRIPTION
**Pull request by wkirby**
This allows users to filter the output of the taxonomy object when included on a post type object.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Why can't you do this in `"rest_prepare_{$this->post_type}"`?

**Comment by wkirby** [comment]
You absolutely can; but if you want to modify the output of the taxonomy everywhere it appears, or just the output of the taxonomy (and no other attributes), this is a simpler approach, and seems like a really inexpensive change.

Compare:

``` php
// Filter Taxonomy Output to `id` => `slug` pairs for two post types
add_filter('rest_prepare_' . POST_TYPE, array(&$this, 'format_taxonomy_output'), 25, 3);
add_filter('rest_prepare_' . POST_TYPE_TWO, array(&$this, 'format_taxonomy_output'), 25, 3);

function format_taxonomy_output($response, $post, $request )
{
    if ( isset($response->data[TAXONOMY]) ) {
        $term_ids = $response->data[TAXONOMY];

        $term_objects = array_map(function($term_id) {
            return get_term_by('id', $term_id, TAXONOMY);
        }, $terms);

        $response->data[TAXONOMY] = wp_list_pluck($term_objects, 'slug', 'term_id');
    }

    return $response;
}
```

With:

``` php
// Filter Taxonomy Output to `id` => `slug` pairs everywhere it appears
add_filter('rest_prepare_terms_' . TAXONOMY, array(&$this, 'format_taxonomy_output'), 25, 3);

function format_taxonomy_output($term_ids, $taxonomy, $post )
{
    $term_objects = array_map(function($term_id) use ($taxonomy) {
        return get_term_by('id', $term_id, $taxonomy->name);
    }, $term_ids);

    return wp_list_pluck($term_objects, 'slug', 'term_id');
}
```

**Comment by danielbachhuber** [comment]
Ok. We'll keep this in mind for the future, but I don't think we're going to add this filter now.

**Comment by wkirby** [comment]
Is there a reason besides you don't feel like it? Filtering the full response object has a few downsides that a more specific filter avoids, namely:
- Need to validate that an attribute is set before attempting to modify it.
- Need to set up another loop if you're looking to perform the same modifications on multiple taxonomies.
- Requires explicit knowledge of the taxonomy details in more places.

By adding a filter you take away no functionality, while increasing the flexibility of the final output.

**Comment by danielbachhuber** [comment]
> Is there a reason besides you don't feel like it?

While it does take a bit more code, this particular need is addressable by an existing filter. Furthermore, I don't want to set precedent of adding filters throughout response preparation for very specific needs.

**Comment by wkirby** [comment]
Fair enough.

**Pull request closed without merging**
