### PR TITLE
Permit creating comments without an assigned post

### LINKED ISSUE #1805: Permit creating comments without `post` argument
> We are actually unwinding Comments and their dependency on Posts in core. You can create Comments that aren't attached to Posts now (comment_post_ID is not required in wp_insert_comment()).

From https://github.com/WP-API/WP-API/pull/1804#issuecomment-162914203

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #1805

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
Hm. I guess I need to wait for #1848 to land

**Comment by danielbachhuber** [comment]
@WP-API/amigos updated. #reviewmerge

**Comment by rmccue** [comment]
Should we allow this? Deferring to @rachelbaker's comment knowledge here.

**Comment by rachelbaker** [comment]
@rmccue @danielbachhuber WordPress allows this programmatically, but not within the Dashboard admin.  Are we trying to match data-model behavior (`wp_insert_comment`) or what the current WordPress allows?

**Comment by danielbachhuber** [comment]
Data model behavior, imo

**Comment by danielbachhuber** [comment]
Why would you permit querying for comments without a post (https://github.com/WP-API/WP-API/issues/1832) but not creating comments without a post?

**Comment by rachelbaker** [comment]
@danielbachhuber Remember when I said:
> We are actually unwinding Comments and their dependency on Posts in core. You can create Comments that aren't attached to Posts now (comment_post_ID is not required in wp_insert_comment()).

It is a slow process

**Pull request merged**
