### PR TITLE
Ensure taxonomy query args are filterable

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
@joehoyle Thoughts on the build failure?

**Comment by kjbenk** [comment]
@danielbachhuber you need to add `tax_query` to the array of valid rest query parameters for the tests to work :)

https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L615-L628

**Comment by danielbachhuber** [comment]
> you need to add tax_query to the array of valid rest query parameters for the tests to work :)

I know — wondering why we aren't doing that right now.

**Comment by BE-Webdesign** [comment]
> I know — wondering why we aren't doing that right now.

That is in #2273 which could use some of your feedback!!

**Comment by rmccue** [comment]
> I know — wondering why we aren't doing that right now.

`tax_query` wasn't allowed because you could have a taxonomy that's non-public and non-REST-enabled, and then query by that. We need to do validation on `tax_query` to ensure all queried taxonomies are allowed.

That's not an issue if we force the parameter to something we're building; i.e. set `$tax_query = []` before we pass it through.

**Comment by rmccue** [comment]
> That's not an issue if we force the parameter to something we're building; i.e. set `$tax_query = []` before we pass it through.

(i.e. it shouldn't be an issue with the way the code is written at the moment, so it should be allowed, I think)

**Comment by kadamwhite** [comment]
PR triage discussion link: https://wordpress.slack.com/archives/core-restapi/p1473802292001233

**Comment by kadamwhite** [comment]
I don't know what to do to suppress that error, could use some help on this

**Comment by kadamwhite** [comment]
After discussion in slack, this PR needs a clear description communicating what it is doing (seems to be permitting tax_query to be used in plugins); and we need to decide whether it is still desired after resolving #2799

**Pull request closed without merging**
