### PR TITLE
Decode HTML entities

### PR DESCRIPTION
**Pull request by axettone**
Added html_entity_decode on text fields in prepare_item_for_response() functions. 

Please do the tests. I hope my contribution was helpful. Anyway, thank you for your work.

Changed files:

        modified:   lib/endpoints/class-wp-rest-attachments-controller.php
	modified:   lib/endpoints/class-wp-rest-comments-controller.php
	modified:   lib/endpoints/class-wp-rest-meta-controller.php
	modified:   lib/endpoints/class-wp-rest-post-types-controller.php
	modified:   lib/endpoints/class-wp-rest-posts-controller.php
	modified:   lib/endpoints/class-wp-rest-taxonomies-controller.php
	modified:   lib/endpoints/class-wp-rest-terms-controller.php
	modified:   lib/endpoints/class-wp-rest-users-controller.php

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks for patching this! These all need extra spaces inside the function call to meet WP coding standards (e.g. `$x = html_entity_decode( $y )`)

We'd also love tests here if you're able to write them. It should be as easy as copy-and-pasting one of the existing ones, and testing using a title like `Harry & Sally` to verify it's passed through untouched.

**Comment by axettone** [comment]
Ok, I’ll fix it ASAP. Thank you for your patience… this is my first contribution to a wordpress-related project! :-D

Bye,
Paolo Niccolò

**Comment by danielbachhuber** [comment]
I think this needs a more global, holistic fix, than a bunch of function calls.

**Comment by axettone** [comment]
Do you have any suggestions?

**Comment by danielbachhuber** [comment]
> Do you have any suggestions?

Not at this time. I think we should continue discussing the options in #1227. No rush to land a fix.

**Pull request closed without merging**
