### PR TITLE
Check taxonomies exist before trying to set properties

### PR DESCRIPTION
**Pull request by joehoyle**
In the case where a develop has unregistered the post_tag / category taxonomy,
it currently produces PHP Notices.

### CODE REVIEW

**Comment by joehoyle** [comment]
@WP-API/amigos #reviewmerge

**Comment by danielbachhuber** [comment]
> In the case where a develop has unregistered the post_tag / category taxonomy,

I'll refrain from commenting about this ;)

**Comment by danielbachhuber** [comment]
@WP-API/amigos anyone know why codecov fails?

**Comment by rmccue** [comment]
@danielbachhuber Because there's no specific testing for this code, so it's not marked as covered. (`codecov/patch` is the coverage for just the changed lines)

**Comment by joehoyle** [comment]
@WP-API/amigos #reviewmerge plz

**Pull request merged**
